### ISSUE TITLE
运行碰到问题

### ISSUE THREAD

**Issue by Gunpowder-pixel** [Spedoske/DataCenterSpeedtest-cli#2]
执行`python3 main.py --list`命令时弹出以下的提示，请问大佬如何解决

```
Traceback (most recent call last):
  File "main.py", line 143, in <module>
    behaviour()
  File "main.py", line 102, in handleList
    print(searchTable)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 70-72: ordinal not in range(128)
```
对了，用的是mac系统，谢谢大佬

**Comment by Spedoske** [comment]
尝试在main.py的开头加上以下语句
```
import sys
import codecs
sys.stdout = codecs.getwriter("utf-8")(sys.stdout.detach())
```

**Comment by Gunpowder-pixel** [comment]
> 尝试在main.py的开头加上以下语句
> 
> ```
> import sys
> import codecs
> sys.stdout = codecs.getwriter("utf-8")(sys.stdout.detach())
> ```

感谢大佬，已成功运行
